[book]
title = "Criterion.rs Documentation"
description = "User Guide and Other Prose Documentation For Criterion.rs"
authors = ["Brook Heisler"]

[output.html]
git-repository-url = "https://github.com/criterion-rs/criterion.rs"

[output.linkcheck]
#follow-web-links = true
exclude = [ 'crates\.io' ]

